### ISSUE TITLE
fix sign up page

### ISSUE THREAD

**Issue by duncangraham** [freindst/Argo-Project-V0#24]
I'm seeing a parse error when I try to sign up
"Uncaught TypeError: Cannot read property 'value' of undefinedtoLogin @ parse.js:5onclick @ signup:1"

I'm betting this is because parse expects some form values that aren't there anymore.

<img width="992" alt="screen shot 2015-07-17 at 6 27 14 pm" src="https://cloud.githubusercontent.com/assets/865298/8758384/7e7202a2-2cb1-11e5-9c14-18f53ff40c63.png">

could you fix this @freindst?

**Comment by freindst** [comment]
the sign up is using username and password to login Parse. Right now, you are not register new user. I will fix it later in the evening.

**Comment by freindst** [comment]
Now it is fixed.

**Comment by duncangraham** [comment]
I'm still getting an error, and why did you add username as a field?

<img width="880" alt="screen shot 2015-07-17 at 10 40 14 pm" src="https://cloud.githubusercontent.com/assets/865298/8760023/d2064e78-2cd4-11e5-8aed-db908167fd55.png">

**Comment by freindst** [comment]
One thing, I think you haven't retrieve the latest version.  I think we are in a different page. I think sign up means register a new user account. Therefore,  a username and password pair is must for login. Maybe you think sign up means put a "bus taker" in parse.

**Comment by duncangraham** [comment]
<img width="885" alt="screen shot 2015-07-17 at 10 47 56 pm" src="https://cloud.githubusercontent.com/assets/865298/8760066/ea017394-2cd5-11e5-84db-0ed8624e45f5.png">

pretty sure i'm all up to date

**Comment by freindst** [comment]
Sorry, I haven't looked carefully enough.

**Comment by duncangraham** [comment]
this is working now

![awesome](http://cdn.gifbay.com/2014/03/dad_youre_an_awesome-122024.gif)
